### ISSUE TITLE
🐛 Bug ➾ Compile current file can misbehave if the text editor is not focused

### ISSUE THREAD

**Issue by AlirezaHaghshenas** [ecadlabs/taqueria#1311]
### 🆘 What happened?

Open a contract source file in the editor, click on Taqueria output window, call "Compile current file"

### 🐘 How impactful is this bug?

🤔 Notable but managable

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AlirezaHaghshenas** [comment]
If we open a contract in the editor, but the focus somewhere else (like the terminal), the "compile current contract" command is still active, but when we invoke it, it does not compile a contract. The solution is to either:
- Disable the command when the text editor is not focused, or:
- Fix the logic to work correctly even when the text editor is not focused, but the current tab in the editor is a contract file

**Comment by hu3man** [comment]
Great, thanks for the context!

Given those two solutions, what is the estimate/lift for each?

**Comment by AlirezaHaghshenas** [comment]
I say maybe half a day or one day

**Comment by MichalLytek** [comment]
I believe it's a bug in the VSCode extension system. The `resourceExtname` in `enablement` is still pointing to the opened text editor but the focused window is vscode side panel (output, debug console) so the `activeTextEditor` is pointing to it but they return a weird, different file path.

So I think they should update `resourceExtname` behavior, so that it should point to the `activeTextEditor.document.uri.path`.
We have issue because of that mismatch.

**Comment by MichalLytek** [comment]
If the potential bug in vscode would be fixed by MS, then our code was ok and everything would be working well.
We can report the bug upstream, so at least we would have confirmation that it was not our fault.

Anyway, #1573 has been merged and it contains a workaround fix for that - a bit hacky but kinda works 😅

**Comment by hu3man** [comment]
Closing as is fixed for now
