### ISSUE TITLE
🚧 Dev ➾ Support Ligo and Michelson Syntax Highlighting in VScE

### ISSUE THREAD

**Issue by hu3man** [ecadlabs/taqueria#1330]
### 🔗 Epic|Feature Link

#1495 

### 🚥 Definition of Done

- [x] 🎯 Planning and Design
- [x] 🏎️ Dev Implementation (PR merged)
- [ ] ✍️ Release Notes Added
- [ ] 🏆 Product Acceptance

### ✅ To Do

- [x] Investigate issues with collisions between 3rd party extensions and Taqueria (ie LIGO)
- [x] Investigate syntax highlighting integration between extensions
- [x] Design and implementation strategy
- [x] Investigate the process for providing language highlighting files to VsCE @hu3man 

### ⚖️ Acceptance Criteria

✨ Functional: 
- [x] Taqueria VScE adds syntax highlighting for Michelson
 
 📐 Non-Functional: 
- [x] Minimize the number of things needing to be installed
- [ ] Minimize the maintenance burden of this feature
 

### 🔭 Scope

🙅‍♂️ Out of Scope: 
- ... 
 
 

### 🧰 Work Description

This ticket covers the work to add syntax highlighting for Michelson and Ligo to Taqueria so that users can have the benefits of syntax highlighting without needing to have any other extensions or programs installed

### 🦄 Sizing

5

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MichalLytek** [comment]
@hu3man I have investigated "issues with collisions between 3rd party extensions and Taqueria (ie LIGO)" by embedding syntax highlighting into taqueria vscode extension 😎 

The good information is that all the other LIGO extensions features related to Language Service Providers works great with taqueria syntax highlighting support:

![Code_Gv8CYBmnrY](https://user-images.githubusercontent.com/10618781/202741842-5284acea-c623-4ebe-b475-6f8bf5e46489.png)

About the syntax highlighting - what I can say so far, looks like the first registered grammar takes precedence.

Here we have taqueria built-in syntax highlighting with removed `// single line comment` support (and ECAD logo for debugging):

![Code_z2TiZUJLl4](https://user-images.githubusercontent.com/10618781/202740804-414d46ae-5991-4851-baf5-a506b06af40c.png)

And after enabling (installing) the LIGO extension, the used grammar is still from taqueria:

![Code_A4eux8dc4U](https://user-images.githubusercontent.com/10618781/202741001-ef22b01b-370b-44a2-ac94-764e66035417.png)

So as far as we keep our definitions in sync with the LIGO team ones, all works great 😉 
But if we get out-of-sync, users might get our old syntax instead of the newest one from LIGO extension.

**Comment by hu3man** [comment]
Thanks for the details. Looking forward to seeing how the Michelson highlighting fits in with this
