### ISSUE TITLE
🚧 Dev ➾ Rewrite tests in taqueria-cli-permissions.spec.ts to use cli-test-library

### ISSUE THREAD

**Issue by hu3man** [ecadlabs/taqueria#1600]
### 🚥 Definition of Done

- [ ] 🎯 Planning and Design
- [ ] 🏎️ Dev Implementation Complete
- [ ] ♾️ PR Merged
- [ ] 🏆 Product Acceptance

### ⚖️ Acceptance Criteria

✨ Functional: 
- [ ] 
- [ ] 

### 🔭 Scope

🙅‍♂️ Out of Scope: 
- ... 
 
 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by michaelkernaghan** [comment]
This will be a low-hanging fruit rewrite.

There is at least one design issue that needs to be resolved before the testing is fully expected for taq calls that require interaction with the config.json.  For now, these will all fail with code 1 and message "your config file is invalid," even though it is ok because there is an inability to get the .taq folder across directory levels.
