### ISSUE TITLE
Refactor handling of stdout/stderr and response object for protocol

### ISSUE THREAD

**Issue by mweichert** [ecadlabs/taqueria#257]
### Describe the feature you would like

Plugins are currently expected to return a JSON serialized message on stdout or stderr like the following:
```
{
  status: 'success',
  stdout: '',
  stderr: '',
  render: 'table'
}
```

This implementation at the protocol layer was an experiment and not something we were committed to. Indeed, there are problems with this approach which will be outlined later in this issue.

Instead, the plugin should be able to write to stdout and stderr and have that relayed by the Taqueria CLI. The plugin should also be able to output a stream that doesn't have to consumed in a memory buffer on the Taqueria-side or plugin-side.

Lastly, we need a means of outputting a structured response object from the plugin to Taqueria. The transport should support multiple encodings, but for now, its fine if Taqueria only has the ability to work with JSON encodings.

The structured response object could also be an exception or TaqError, and therefore will need to be able to accommodate multiple response types.

To test the refactoring, within the scope of this issue we should also refactor the type generation plugin.

### Is this feature solving a problem?

The current implementation has the following problems:
- It isn't a pleasant developer experience for plugin authors. It's natural for a developer to expect that they can just log output using `console.log` or `console.error`.
- It imposes an unnecessary restriction for a plugin developer to wrap their output.
- It makes plugin authoring and debugging harder. A developer can't output something to console.log for debugging purposes.
- It requires buffering stdout and stderr. The plugin can't provide streaming output

### Please share any additional details you have?

Some thoughts about how to consume the output on the Deno/Taqueria side:
https://stackoverflow.com/questions/66861364/stream-stdout-from-subprocess

I would emphasize that in the implementation and refactoring effort we keep the following in mind:

> How do we keep the protocol itself (transport between plugins and Taqueria) simple and concise? By keeping the protocol itself small and with fewer restrictions and opinions, it becomes easier for plugin authors to understand. It also reduces friction for developers looking to develop an SDK for another language or platform, such as a Python SDK.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ricklove** [comment]
Thoughts:

- Make it work with normal stdout/stderr - which is streamed directly to console
  - Allow console.error to stream directly to console (instead of treating it like a failure or a throw error).
- Add a way to send structured message to the parent process. 
  - i.e. the sdk would have a sendResponse function which would somehow send the message to the parent process as json.
  - This could be through the stdout stream, by using a <STRUCTURED...></STRUCTURED> tag
  - The deno process would preview all text and intercept structured messages, but allow other text to go to console
- Wrap the task process (in the sdk) in a try/catch and use the `sendErrorResponse` that works similar to above
