### ISSUE TITLE
Basic contract metadata support

### ISSUE THREAD

**Issue by russellmorton** [ecadlabs/taqueria#324]
As a smart contract developer, I want to create, edit and delete and publish *basic* contract metadata to my project

Metadata should be in line with TZIP16 - https://tzip.tezosagora.org/proposal/tzip-16/

Consider:
- TZIP20 - https://tzip.tezosagora.org/proposal/tzip-20/
- TZIP21 - https://tzip.tezosagora.org/proposal/tzip-21/
- Taquito TZIP-16 Contract Metadata and Views - https://tezostaquito.io/docs/metadata-tzip16/
- Taquito TZIP-12 Token Metadata - https://tezostaquito.io/docs/tzip12/

## Creation / Generation

- Global metadata
 - Collected when the user first runs taqueria
 - Persisted to home directory (like opt-in data)
   - Data collected
    - Author (name and e-mail)
    - License
- Project metadata
  - Collected when the user first runs taq init or taq scaffold
  - Persisted to config.json file
  - Data collected
    - Name
    - Description
    - Homepage
    - Authors
    - License (override)
- Contract Metadata:
  - Collected when taq register [contract] is executed
  - Persisted to artfiacts/[contractFilename].json
  - Data:
    - Name (override)
    - Description (override)
    - Version (defaults to md5sum)
    - Homepage (override)
    - License (override)
    - Authors (override)
    - Interfaces
    - If interfaces includes TZIP-12:
      - Name
      - Symbol
      - Decimals

## Validation _Deferred_
Using TZComet
Using Taquito
Compiler validation
Potentially a separate plugin

## Publishing
- Publish via IPFS
- Future consideration:
  - Internal storage
  - HTTP

## Implementation Considerations
- Need to implement hooks
- Collecting global and project-level metadata is done in the CLI (What happens with VS Code? @mweichert)
- Develop a metadata plugin which adds a template called 'metadata'. The user would create an instance of that template just like any other template - `taq create metadata [contractName]`. If invoked with no additional arguments, it would prompt you for each field listed above, however, you could bypass certain fields by passing values as flags. E.g.: `taq create metadata hello.mligo --name "Hello World"`
- Using hooks, we call `taq create metadata` when `taq register [contract]` is called, whether that be directly or indirectly.
- #550 for npm init on taq init
- Implement extended JSON file with commented guidance around contract metadata
- Bigmap instantiation

**USE CASE**
Generate JSON -> Publish to IPFS -> Add hash to contract

**ACCEPTANCE CRITERIA**
- [ ]  `taq apply-project-meta` applies project-level metadata to each contract
- [ ] `taq create global-metadata` task creates project-level contract 
- [ ] `taq create project-metadata` task creates project-level contract 
- [ ] `taq create metadata [contractName]` creates contract metadata 
- [ ] URI and hash store in state (skip)
- [ ] Metadata JSON file stored in artifacts folder
- [ ] Ability to delete metadata for a contract (no action required)
- [ ] Ability to update metadata for a contract (no action required)
- [ ] Abiility to view metadata for a contract (no action required)
- [ ] Ability to publish metadata - use ipfs-pinata upload (no action required)
- [ ] Have the ability to take in properties for metadata (all input should be optional):
  - [ ] Author name(s)
  - [ ] Email(s)
  - [ ] Homepage
  - [ ] Description
  - [ ] Version
  - [ ] Licence
  - [ ] Authors
  - [ ] Homepage
  - [ ] Source
  - [ ] Interfaces
- [ ] Publish to contract metadata to IPFS
- [ ] Basic contract metadata documentation updated
- [ ] Test suite updated

**DEFERRED**

- [ ] Metadata validation
- [x] #233

**Comment by mweichert** [comment]
Thoughts:

Adjust the init task to ask for:
1) author name and e-mail. Could be multiple.
2) home page

The above would be used as default values for the "author" and "homepage" meta fields for contracts.

Additionally, I think we need to extend the scaffolding as we've talked about earlier.

Plugin would expose a new field called "scaffolds" and would look like this:

```
scaffolds: [
    Scaffold.create({
      name: "mligo",
      description: "Blank contract using mligo syntax",
      alias: "ml",
      options: [],
      handler: "proxy",
      type: "contract"
    })
]
```

The interface for defining a scaffold would be very familiar as it closely resembles the interface for defining a task. The important thing to note there is the "type" field, which will inform the end-user what kind of scaffold this is.

Developers could then scaffold the a contract like this:

`taq scaffold mligo increment.mligo`

Just like tasks, we can resolve conflicts using the --plugin argument:

`taq scaffold example increment.jsligo --plugin ligo` would scaffold increment.jsligo using the example scaffold from the ligo plugin.

We'd also add a `list scaffolds` tasks to list the available scaffolds that the installed plugins have exposed. This would display a table with name, description, and type columns.

Finally, we add a metadata plugin which exposes a scaffold for generating tzip-16 metadata.

```
scaffolds: [
    Scaffold.create({
      name: "TZIP16",
      description: "TZIP16 metadata for the given contract",
      alias: "meta",
      options: [{
        flag: "contract",
        type: "contract",
        description: "The filename of the contract to generate metadata for"
      }],
      handler: "proxy",
      type: "contract"
    })
]
```

This would allow users to generate TZIP16 metadata for an existing contract:

`taq scaffold meta --contract increment.mligo increment.json`

When they run that, the metadata plugin would prompt them for:
- name (default to filename without extension)
- description
- version
- license

With that information, the task would generate an artifact called increment.json that would look like this (without my inline comments):
```
{
  "name": "increment",
  "description": "Sample increment contract",
  "version": "0.0.1",
  "license": "GPLv2",
  
  // Taken from init task
  "authors": ["Michael Weichert <michael.weichert@ecadlabs.com>"],
  "homepage": "https://mweichert.com" ,
  
  "source": {
    "tools": ["ligo", "taqueria"],
    
    // Extracted from git origin
    "location": "https://github.com/foo/bar" 
  },
  "interfaces": ["TZIP-16"]
}
```

We can add the following later:
- Metadata validation via third-party tools
- Implement hooks, so that running "scaffold mligo increment.mligo" also runs "metadata --contract increment.mligo increment.json"
