### ISSUE TITLE
[EPIC] Create tezos-client plugin with typecheck and simulate tasks

### ISSUE THREAD

**Issue by russellmorton** [ecadlabs/taqueria#547]
As a smart contract developer I want to have a tezos-client plugin and run tezos-client tasks inside of my Taqueria project so that I can easily interact with my project using the tezos-client.

*** As per @hu3man @mweichert @jchenche discussion Apr 27th ***
- We will be implementing this functionality in a new `tezos-client` plugin rather than as part of flextesa
- Initially, the plugin will support 2 tasks: simulate, and typecheck
- The sandboxName parameter will be made optional, and if not provided, the CLI should use the default sandbox configured in `config.json`
- Any required parameters will be implemented as positional arguments
- The structure of the typecheck task command will be `taq typecheck [sourceFiles]` (with -s/--sandboxName as an optional flag)
- The typecheck task will first scan the /artifacts dir, then the /contracts dir, and process the first instance of a file matching the provided name (if a filename is specified), and if not, process any michelson files encountered in either folder
- The simulate task will use the command `taq simulate <sourceFile> <input>` (with -i/--initial-storage, and -s/--sandboxName as optional flags)
- If the simulate task does not receive a value for initial storage from the CLI command, it should look in `config.json`, and use the value provided there for the contract being simulated
- For the first iteration (MVP), the plugin will only support using the Tezos client in the Flextesa sandbox (but can be targeted to various env's in future releases
- It may be useful to provide a basic `taq client 'insert tezos-client command here'` task which would allow the dev the flexibility to run any tezos-client cli command from within Taqueria

**ACCEPTANCE CRITERIA**
- [x] #557
- [x] #558
- [x] #619
- [x] #604 

**ADDITIONAL LINKS**
- https://try-michelson.com/
  - https://gitlab.com/nomadic-labs/try-michelson
- https://marketplace.visualstudio.com/items?itemName=baking-bad.michelson
- https://marketplace.visualstudio.com/items?itemName=serokell-io.michelson-debugger
- https://gitlab.com/morley-framework/morley-debugger
- https://tezos.gitlab.io/michelson-reference/

**Comment by russellmorton** [comment]
@jchenche please will you include the details you and @mweichert have discussed here?

**Comment by russellmorton** [comment]
Updating this ticket to track the Tezos client plugin.

@hu3man @mweichert @jchenche

**Comment by jchenche** [comment]
Dropping simulate and only do type-checker after discussion with @mweichert

**Comment by russellmorton** [comment]
@hu3man we probably need to move this to the epic board and do additional slicing on this.

**Comment by jchenche** [comment]
After more discussions with @mweichert, we've decided to expose both `typechecker` and simulate (`run script`) tasks via the existing `flextesa` plugin

**Comment by russellmorton** [comment]
@jchenche please add details as a comment on the discussion.

**Comment by jchenche** [comment]
We are using the existing `flextesa` plugin because it already has all the configurations set for `tezos-client` within the `flextesa` docker image. So we won't be needing a new (tezos-client) plugin.

**Comment by hu3man** [comment]
Do you have a PR you can link to this issue @jchenche?

**Comment by jchenche** [comment]
@hu3man not yet. I will get one up once it's done

**Comment by hu3man** [comment]
Draft PR's are great for this and give you the advantage of the build/test pipeline status while developing

**Comment by jchenche** [comment]
Good idea!

**Comment by hu3man** [comment]
I'd like to start thinking about the best way to document this so the feature is discoverable and easy to use. Given that the functionality is being shoehorned into the Flextesa plugin due to technical and implementation reasons which may not make sense to the end-user, I think we should start discussing this asap

The tasks live in the Flextesa plugin and would normally live in the Flexteasa plugin docs, but given that the functionality is unique from sandbox functionality, I can see it also living in a separate section called 'Type Checking' or similar. Given that it's not an independent plugin, this file would live under `getting started` or a new category if we went that route

What does the team think is the best approach here?

Also, are we planning on leaving this in Flextesa going forward, or is this a short-term solution that may be re-factored into a separate plugin at some point?

**Comment by jchenche** [comment]
I am wondering if we could have a page in the Taqueria document website for **all** "tasks". Maybe a table with the first column for task names and second table for the plugin that has this task.

Furthermore, the page would have a section for "most commonly used tasks" to make it easy for new users to find what they're looking for.

This general solution will also fix @hu3man's concern. Thoughts?

**Comment by hu3man** [comment]
While that separate task page is a good idea @jchenche and something we should implement, the average user will likely not find the information buried that deep and thus may not discover the Type Checking feature

Generally, we would want to expose major functionality in the navbar as its own page and given that this was originally going to be a separate plugin, it has a unique set of content (purpose, commands, steps for use, input/output) from my understanding. Is this correct or is it more closely tied to Flextesa/sandboxes?

Since it's functionality is quite different both conceptually and in use (separate flow and problem a user is solving when type checking vs managing a sandbox), I would advocate for a separate page which could either live in `getting started`, or in `plugins`; but neither is correct really...

**Comment by jchenche** [comment]
I am not sure which is a better way. But if I was a user and I want a **task** that does **type checking**, I'd go to this "task page" and search up something like "type" or "checking" or "type checking" or "typechecking".

**Comment by hu3man** [comment]
Is there a plan to make this a standalone plugin at some point? If so I think there is a case to be made for creating a page in the plugin section

**Comment by jchenche** [comment]
I don't remember any concrete plans but I think @mweichert said we may make this a standalone plugin at some point (not sure when)

**Comment by russellmorton** [comment]
The way this functionality has been introduced has me thinking that the term plugin for this may not be the best descriptor for this in the long run.

> Also, are we planning on leaving this in Flextesa going forward, or is this a short-term solution that may be re-factored into a separate plugin at some point?

The value of this is as an add-on to the Flextesa plugin. It cannot stand on its own at this point so it feels to me that this should be positioned more as a plugin add-on rather than a plugin. I know this introduces another level of complexity so we can discuss this.

> I'd like to start thinking about the best way to document this so the feature is discoverable and easy to use. Given that the functionality is being shoehorned into the Flextesa plugin due to technical and implementation reasons which may not make sense to the end-user, I think we should start discussing this asap
> 
> The tasks live in the Flextesa plugin and would normally live in the Flexteasa plugin docs, but given that the functionality is unique from sandbox functionality, I can see it also living in a separate section called 'Type Checking' or similar. Given that it's not an independent plugin, this file would live under `getting started` or a new category if we went that route
> 
> What does the team think is the best approach here?

A new section for 'Type Checking' seems like the best solution for me. This can then be referenced in the getting started section for those that enter through there, but users more familiar with Taqueria could also seek this out and not expect it in a getting started section.

**Comment by hu3man** [comment]
Thanks for the context @russellmorton, will implement it like that for now

**Comment by hu3man** [comment]
The docs have been implemented in PR #672

@jchenche , @alexzbusko, are the acceptance criteria met for the tests yet? If so let's move this to ready for release 🚀
