### ISSUE TITLE
[Feature]: Disambiguate Warnings and Errors

### ISSUE THREAD

**Issue by russellmorton** [ecadlabs/taqueria#944]
### Describe the feature you would like

As a smart contract developer I want to easily see the difference between Warnings and Errors that are thrown by Taqueria.

It is difficult to tell whether Taqueria is throwing a warning or an error and it will be useful to have the difference highlighted more succinctly for the user.

### Is this feature solving a problem?

Details about the problem your feature solves

### Please share any additional details you have?

Details about the problem your feature solves

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by russellmorton** [comment]
@AlirezaHaghshenas, we have an issue for the warnings and errors. Please will you add the details as raised this morning?

**Comment by AlirezaHaghshenas** [comment]
In some cases, there is no distinction between warnings and errors (like in origination, lack of storage is an error, but lack of default account is just a warning).
We need a standardized way to make this distinction in CLI and in TVsCE, so that in VsCode we can show the appropriate feedback to the user.
